### ISSUE TITLE
Does ist work with typedoc ^0.23.26

### ISSUE THREAD

**Issue by opt12** [droppedcode/typedoc-plugin-relative-includes#1]
I'was glad to find this typedoc plugin, as I'd like to include some markdown files in my documentation.
I'd like to keep the markdown files out of a centralized assets folder, but want to add them side-by-side with the files they explain.

Unfortunately however, I'm not getting this plugin to do anything.

I include my markdown file like this:
```/**
 * [[include: ./patient.service.md]]
 * Business logic for patient data.
 */
```

But in the output, all I get is:

----------------
# Class PatientService
[[include: ./patient.service.md]] Business logic for patient data.

--------------
So it is not included at all.
For this experiment I had to leave th typedoc-option for `"includes"` undefined. Otherwise, it would complain not finding the file `patient.service.md` in the folder that was specified as the assets folder for typedoc.

Thanks for any hints!

**Comment by droppedcode** [comment]
Hi Felix,

The plugin was not updated to typedoc 0.23 yet.
I have fixed it, added a little bit more information to the readme and added a tests folder where you can a few use cases.

What is important that you have to specify the include folder in the typedoc options.

If you have any other problem or is it not working, please reopen the ticket.

**Comment by opt12** [comment]
@droppedcode Thanks for the sudden service.
Works like a charm now!
